default: cpsc2150/MyDeque/ArrayDeque.java/IDeque.java/ListDeque.java/AbsDeque.java
	javac cpsc2150/MyDeque/ArrayDeque.java/IDeque.java/ListDeque.java/AbsDeque.java

run: cpsc2150/MyDeque/ArrayDeque.class/IDeque.class/ListDeque.class/AbsDeque.class
	java cpsc2150.MyDeque.DequeApp.java
	java cpsc2150.MyDeque.CharacterDequeApp.java

clean:
	rm -f cpsc2150/MyDeque/*.class